biome-tool: 369
meta-tool: 280
antigravity:
- ANVIL
- BED_BLOCK
- BROWN_MUSHROOM
- CACTUS
- CARPET
- DEAD_BUSH
- FLOWER_POT
- GOLD_PLATE
- IRON_DOOR_BLOCK
- IRON_PLATE
- LADDER
- LEVER
- LONG_GRASS
- PORTAL
- RAILS
- RED_MUSHROOM
- RED_ROSE
- REDSTONE_TORCH_ON
- REDSTONE_TORCH_OFF
- SIGN
- SIGN_POST
- SNOW
- STATIONARY_WATER
- STATIONARY_LAVA
- STONE_BUTTON
- SUGAR_CANE_BLOCK
- TORCH
- TRAP_DOOR
- VINE
- WALL_SIGN
- WATER_LILY
- WOOD_BUTTON
- WOODEN_DOOR
- WOOD_PLATE
- YELLOW_FLOWER
cycler-blacklist: