name: KCycler
main: fr.mrkold.kcycler.MainClass
version: '1.0.1'
author: MrKold
depend: [WorldGuard]
softdepend: [PlotMe]
commands:
    mt:
      description: Give MetaTool
    bt:
      description: Give BiomeTool
    ph:
      description: /ph <playername> give <playername>'s head
