biome-tool: 369
meta-tool: 280
prevent-leaves-decay: true
antigravity:
- ANVIL
- BED_BLOCK
- BROWN_MUSHROOM
- CACTUS
- CARPET
- DEAD_BUSH
- FLOWER_POT
- GOLD_PLATE
- IRON_DOOR_BLOCK
- IRON_PLATE
- LADDER
- LEVER
- LONG_GRASS
- PORTAL
- RAILS
- RED_MUSHROOM
- RED_ROSE
- REDSTONE_TORCH_ON
- REDSTONE_TORCH_OFF
- SIGN
- SIGN_POST
- SNOW
- STATIONARY_WATER
- STATIONARY_LAVA
- STONE_BUTTON
- SUGAR_CANE_BLOCK
- TORCH
- TRAP_DOOR
- VINE
- WALL_SIGN
- WATER_LILY
- WOOD_BUTTON
- WOODEN_DOOR
- WOOD_PLATE
- YELLOW_FLOWER
cycler-blacklist:
pick-blacklist:
- 44
- 126
- 53
- 67
- 108
- 109
- 114
- 128
- 134
- 135
- 136
- 156
- 163
- 164
- 54
- 58
- 61
- 65
- 130
- 145
- 146
- 323
- 23
- 29
- 33
- 69
- 77
- 96
- 131
- 143
- 158
- 324
- 330
- 356
- 404
- 27
- 28
- 66
- 157