name: KCycler
main: fr.mrkold.kcycler.KCyclerPlugin
version: "${project.version}"
author: MrKold
softdepend: [WorldGuard, PlotSquared]
commands:
    mt:
      description: Give MetaTool
    bt:
      description: Give BiomeTool
    ph:
      description: /ph <playername> give <playername>'s head